// Posts
export const REMOVE_POST = 'REMOVE_POST';
export const CREATE_POST = 'CREATE_POST';
export const ADD_POST_LIKE = 'ADD_POST_LIKE';
export const REMOVE_POST_LIKE = 'REMOVE_POST_LIKE';
export const SET_POSTS = 'SET_POSTS';

// Notifications
export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION';
export const DESTROY_NOTIFICATION = 'DESTROY_NOTIFICATION';
export const RESET_NOTIFICATION = 'RESET_NOTIFICATION';

// Post
export const SET_POST = 'SET_POST';
export const ADD_ACTIVE_POST_LIKE = 'ADD_ACTIVE_POST_LIKE';
export const REMOVE_ACTIVE_POST_LIKE = 'REMOVE_ACTIVE_POST_LIKE';