// Profile
export const SET_PROFILE = 'SET_PROFILE';
export const SET_PROFILE_IMAGES = 'SET_PROFILE_IMAGES';
export const SET_PREVIEW_IMAGES = 'SET_PREVIEW_IMAGES';
export const CREATE_FOLLOW = 'CREATE_FOLLOW';
export const DESTROY_FOLLOW = 'DESTROY_FOLLOW';

// Posts
export const REMOVE_POST = 'REMOVE_POST';
export const CREATE_POST = 'CREATE_POST';
export const ADD_POST_LIKE = 'ADD_POST_LIKE';
export const REMOVE_POST_LIKE = 'REMOVE_POST_LIKE';
export const SET_POSTS = 'SET_POSTS';
export const LOAD_MORE_POSTS = 'LOAD_MORE_POSTS';

// Notifications
export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION';
export const DESTROY_NOTIFICATION = 'DESTROY_NOTIFICATION';
export const RESET_NOTIFICATION = 'RESET_NOTIFICATION';

// Post
export const SET_POST = 'SET_POST';
export const ADD_ACTIVE_POST_LIKE = 'ADD_ACTIVE_POST_LIKE';
export const REMOVE_ACTIVE_POST_LIKE = 'REMOVE_ACTIVE_POST_LIKE';
export const SET_COMMENTS = 'SET_COMMENTS';
export const RESET_COMMENTS = 'RESET_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const ADD_COMMENT_LIKE = 'ADD_COMMENT_LIKE';
export const REMOVE_COMMENT_LIKE = 'REMOVE_COMMENT_LIKE';

// Explore
export const SET_POPULAR_USERS = 'SET_POPULAR_USERS';
export const SET_POPULAR_POSTS = 'SET_POPULAR_POSTS';